
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-zentralesportal
  name: ms-zentralesportal
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: ms-zentralesportal
status:
  loadBalancer: {}