
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-zentralesportal
  name: ms-zentralesportal
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    app: ms-zentralesportal
status:
  loadBalancer: {}